### ISSUE TITLE
ひらがなをカタカナに変換し表記する際の規則

### ISSUE THREAD

**Issue by pjiyoung11** [ikawaha/kagome.ipadic#21]
こんいちは、韓国で勉強している人です。kagomeライブラリーでひらがなをカタカナ発音表記に変換する時、特に長音の表記が場合によって違うように見えますが、どのような日本語の規則によって変換するのかを伺いたいです。例えば、

１。一般的の長音：’ー’で表記
例）そう　→　ソー　
例）ほう　→　ほー
２。半濁点の付く長音：’ー’で表記
例）ぽう　→　ポー
３。濁点の付く長音：’う’を生かして表記
例）ぞう　→　ゾウ
例）ぼう　→　ボウ

ここで、同じ長音なのに３番の’濁点がつく場合’のみ’う’を生かして表記する理由を伺いたいです。よろしくお願いします。

**Comment by ikawaha** [comment]
kagome.ipadic では ipadic version 2.7.0 を形態素解析の辞書として利用しています。この辞書は形態素解析器「茶筌(Cha-Sen)」用の日本語辞書として公開され、その後開発された様々な形態素解析器([mecab](https://taku910.github.io/mecab/), kuromoji など)でも利用されています。

kagome.ipadic での発音表記も、この辞書の内容を出力しているだけなので、ご指摘のような発音表記の揺れがあることも知りませんでした。少し調べてみたところ、ipadic のマニュアルによると、「発音」のフィールドは、version 2.0 以降に外部の研究成果を取り入れる形で追加されたようです。

ipadic マニュアルより引用：

>    ipadic2.0以降の辞書では，単語に新たに「発音」フィールドが追加された．これは，「日本語ディクテーション基本ソフトウェアの開発」グループの努力により添付されたものである．例えば，係助詞の「は」の読みは「ワ」，「常識」の読みは「ジョーシキ」のように長音は「ー」によって示されている．また，綴りも品詞も等しいが読みだけが異なる単語，例えば，「私(ワタシ/ワタクシ)」については，{ワタシ/ワタクシ}のようにすべての可能な読みを付与し，一つの語として登録した.

日本語ディクテーション基本ソフトウェアの開発については成果報告がいくつか上がっているので、深掘りしていけば発音表記が揺れる原因が分かるかもしれません。

お答えになりませんが、何かの参考になれば幸いです。

関連研究：
日本語ディクテーション基本ソフトウェア（99年度版）
https://www.jstage.jst.go.jp/article/jasj/57/3/57_KJ00001457638/_pdf/-char/ja
日本語ディクテーション基本ソフトウェア（98年度版）
https://www.jstage.jst.go.jp/article/jasj/56/4/56_KJ00001457343/_pdf/-char/ja

ipadic version 2.7.0 ユーザーズマニュアル
http://sils.shoin.ac.jp/~gunji/AI/Kyozai/ChaSen/ipadic-2.7.0-ja.pdf

**Comment by ikawaha** [comment]
直接の資料ではありませんが、こちらが参考になるかもしれないと教えてもらいました。
https://ipsj.ixsq.nii.ac.jp/ej/?action=pages_view_main&active_action=repository_view_main_item_detail&item_id=48520&item_no=1&page_id=13&block_id=8

**Comment by pjiyoung11** [comment]
@ikawaha 親切なご説明ありがとうございます。追加してくださった資料もよく読んでみます。教えてくださった内容によると、今のところkagomeだけではなく一般に公開されているほとんどのライブりらーも全部同じく発音表記の譲れがあるでしょうね。。。わかりました。自分ももう少し調べてみます。：）
