### ISSUE TITLE
Memory saving

### ISSUE THREAD

**Issue by ikawaha** [ikawaha/kagome.ipadic#7]
Using kagome.ipadic on GAE/Go needs at least B4 instance.
Is it possible to save memory to be operated on a cheaper instance?

**Comment by ikawaha** [comment]
Kazzz=san reported that the memory usage of kagome reaches 159 MB.
Thank you !

![image](https://cloud.githubusercontent.com/assets/4232165/26301947/a6c968c8-3f1d-11e7-922e-e731d24ae1d9.png)

<blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">kagome、GAE standard environment にデプロイして実行してみた。やはりメモリ足りなくて落ちるぽい。<br><br>F1インスタンスで実行したが、kagomeはトークンナイザの初期化で159MBのメモリを要求するためF1(128M)では初期化すらできないぽいです。 <a href="https://t.co/2VaRVaR2KC">pic.twitter.com/2VaRVaR2KC</a></p>&mdash; かず@GAE/Go始めました (@Kazzz) <a href="https://twitter.com/Kazzz/status/866585088401719296">2017年5月22日</a></blockquote>

**Comment by ikawaha** [comment]
humm...

> Kazzz: kagome on appengine、F2インスタンス(メモリ256MB)だと動いた!!  残りメモリ3MB ww pic.twitter.com/fCK6GXU9iv

![dabav8xw0aedt2g](https://cloud.githubusercontent.com/assets/4232165/26333546/546b4e62-3f99-11e7-99ce-e6fdaf2438c7.jpg)

**Comment by ikawaha** [comment]
It seems that memory usage can be compressed to 98 MB by pr #9.
Thank you reporting @Kazzz=san !

<blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr"><a href="https://twitter.com/ikawaha">@ikawaha</a>さんの日本語形態素解析エンジンkagome.ipadic、最新の「品詞のみオプション」をGAEで試してみました。<br><br>なんとF1インスタンスでも動作しました!! ＼(^o^)／<br><br>メモリ消費は97.5MBと、通常版に比較して156MB削減されてます。<br>これは凄い!! <a href="https://t.co/4WZzaWUHoI">pic.twitter.com/4WZzaWUHoI</a></p>&mdash; かず@GAE/Goやってます (@Kazzz) <a href="https://twitter.com/Kazzz/status/869698724741566468">2017年5月30日</a></blockquote>

![dbhksayvwaeacjp](https://cloud.githubusercontent.com/assets/4232165/26612560/8d89e408-45f0-11e7-90d7-476c1dd184f0.jpg)

**Comment by Kazzz** [comment]
ikawaha san! 

This is a fantastic job.
I think that it is most suitable for Japanese morpheme analysis engine used in GAE / Go.
